blank_issues_enabled: false
contact_links:
  - name: 💬 Questions et Support
    url: https://github.com/jolanallen/oxiddd/discussions
    about: Utilisez les discussions pour poser des questions ou demander de l'aide.
